# SPIGOT CONFIGURATION
# DO NOT USE REVIEW SECTION FOR BUGS.
# DISCORD: hknn#8888

# PERMISSIONS
# NOTIFY: acnotify.see, RELOAD: acnotify.reload

# MESSAGES
messages:
  prefix: '&8[&3ACNotify&8]&r'
  reloaded: '%prefix% &aPlugin has been reloaded.'
  no-permission: '%prefix% &cYou do not have permission to use this command.'
  only-console: '%prefix% &cThis command can only be used by a console.'

# SETTINGS
settings:
  # Enable this if you want to send notify messages to every server on your network.
  bungeecord: false

  # Disable this if you don't want prefix on notify command.
  prefixForNotifyMessages: true

  # This is required for BungeeCord Auto Notify.
  server-name: 'LOBBY-1'

# AUTO NOTIFY (This feature will send notify messages automatic when a warning comes from anti cheat plugin.)
# This feature supports BungeeCord mode.
# Auto Notify feature supports these anti cheats: Spartan, Reflex and Matrix.
auto-notify:
  enabled: false
  min-violation: 1
  format: '%prefix% &e%player%&8:&c %hack% &8(&cVL&8:&c %vls%&8) &8| &7Ping&8:&a %ping% ms &8| &7Server:&9 %server%'